---
- name: Identify primary controller
  ansible.builtin.set_fact:
    primary_controller: "{{ groups['k8s_controllers_init'] | first }}"

- name: Compute Kubernetes version strings
  ansible.builtin.set_fact:
    kubernetes_minor_string: "{{ kubernetes_major_version }}.{{ kubernetes_minor_version }}"
    kubernetes_full_version: "{{ kubernetes_major_version }}.{{ kubernetes_minor_version }}.{{ kubernetes_patch_version }}{{ kubernetes_package_suffix }}"

- name: Load kernel modules
  ansible.builtin.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Persist kernel modules
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
    mode: '0644'

- name: Apply sysctl
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1
    mode: '0644'

- name: Reload sysctl
  ansible.builtin.command: sysctl --system
  changed_when: false

- name: Install containerd
  include_role:
    name: geerlingguy.containerd

- name: Add Kubernetes repo key
  ansible.builtin.get_url:
    url: "https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_minor_string }}/deb/Release.key"
    dest: /etc/apt/keyrings/kubernetes-release.key
    mode: '0644'

- name: Check if joined
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: joined

- name: Get join command from primary controller
  ansible.builtin.set_fact:
    control_plane_join_cmd: "{{ hostvars[primary_controller].control_plane_join_cmd }}"
  when: not joined.stat.exists

- name: Join control plane
  ansible.builtin.command: "{{ control_plane_join_cmd }}"
  when: not joined.stat.exists
  become: true

- name: Output success
  ansible.builtin.debug:
    msg: "Controller {{ inventory_hostname }} successfully joined."
